services:
  restapi:
    image: fremux-backend
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8001:8000"
    entrypoint: ["python3", "main.py"]
    networks:
      - fremux_net
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fremux
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - fremux_net
  minio:
    image: minio/minio
    command: server --console-address :9005 /data
    ports:
      - '9000:9000'
      - '9005:9005'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    restart: always
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - fremux_net
networks:
  fremux_net:
    external: true